export const dummyPopularCrews = [
  {
    id: 1,
    name: "한강 야경 러닝",
    description: "야경 즐기며 한강을 함께 달려요",
    category: "운동/영상",
    tags: ["러닝", "야경", "서울", "건강"],
    imageUrl: "",
  },
  {
    id: 2,
    name: "요리하고 같이 먹자",
    description: "요리도 하고 소셜다이닝도 함께",
    category: "음식",
    tags: ["요리", "소셜", "식사", "홈파티"],
    imageUrl: "",
  },
  {
    id: 3,
    name: "버스킹크루",
    description: "기타 치는 사람 모여라!",
    category: "음악/악기",
    tags: ["기타", "버스킹", "공연", "악기"],
    imageUrl: "",
  },
  {
    id: 4,
    name: "전시 같이 가요",
    description: "주말마다 전시나 미술관 가기",
    category: "문화/공연",
    tags: ["전시", "미술", "문화", "데이트"],
    imageUrl: "",
  },
  {
    id: 5,
    name: "서울사진산책",
    description: "사진 찍으며 서울 곳곳 산책해요",
    category: "사진/영상",
    tags: ["사진", "서울", "산책", "DSLR"],
    imageUrl: "",
  },
  {
    id: 6,
    name: "자기계발 챌린지",
    description: "매일 한시간씩 함께 성장해요",
    category: "자기계발",
    tags: ["공부", "자기계발", "습관", "루틴"],
    imageUrl: "",
  },
  {
    id: 7,
    name: "2030 스포츠 직관러",
    description: "같이 야구, 축구 직관해요!",
    category: "스포츠직관",
    tags: ["야구", "축구", "응원", "직관"],
    imageUrl: "",
  },
  {
    id: 8,
    name: "한강 돗자리 모임",
    description: "돗자리 깔고 수다 타임",
    category: "사교",
    tags: ["돗자리", "수다", "피크닉", "사교"],
    imageUrl: "",
  },
  {
    id: 9,
    name: "자연 속으로",
    description: "트래킹, 등산 같이 가실 분?",
    category: "액티비티",
    tags: ["트래킹", "등산", "자연", "건강"],
    imageUrl: "",
  },
  {
    id: 10,
    name: "스페인어 같이 공부해요",
    description: "기초부터 함께 시작해요",
    category: "스터디",
    tags: ["스페인어", "외국어", "스터디", "자기계발"],
    imageUrl: "",
  },
  {
    id: 11,
    name: "주말 서울 투어",
    description: "서울 숨은 명소 탐방",
    category: "여행",
    tags: ["서울", "투어", "여행", "일상탈출"],
    imageUrl: "",
  },
  {
    id: 12,
    name: "크로스핏 챌린지",
    description: "헬스장 대신 크로스핏 도전!",
    category: "운동/영상",
    tags: ["크로스핏", "운동", "도전", "근력"],
    imageUrl: "",
  },
  {
    id: 13,
    name: "밴드 모임",
    description: "밴드 만들어서 공연해요",
    category: "음악/악기",
    tags: ["밴드", "보컬", "연습", "합주"],
    imageUrl: "",
  },
  {
    id: 14,
    name: "혼영 탈출 크루",
    description: "혼자 말고 같이 영화 보자",
    category: "문화/공연",
    tags: ["영화", "영화관", "팝콘", "데이트"],
    imageUrl: "",
  },
  {
    id: 15,
    name: "일요 등산 모임",
    description: "매주 일요일 서울 근교 등산",
    category: "액티비티",
    tags: ["등산", "산", "건강", "주말"],
    imageUrl: "",
  },
  {
    id: 16,
    name: "디지털노마드 스터디",
    description: "프리랜서끼리 정보 공유",
    category: "스터디",
    tags: ["디지털노마드", "프리랜서", "공부", "자기계발"],
    imageUrl: "",
  },
  {
    id: 17,
    name: "사진 잘 찍고 싶어요",
    description: "사진 스터디 & 출사",
    category: "사진/영상",
    tags: ["사진", "출사", "공부", "카메라"],
    imageUrl: "",
  },
  {
    id: 18,
    name: "혼밥 탈출단",
    description: "같이 밥 먹을 사람 모여라",
    category: "음식",
    tags: ["혼밥", "밥친구", "사교", "맛집"],
    imageUrl: "",
  },
  {
    id: 19,
    name: "글쓰기 챌린지",
    description: "하루 30분 글쓰기 공유",
    category: "자기계발",
    tags: ["글쓰기", "습관", "기록", "성장"],
    imageUrl: "",
  },
  {
    id: 20,
    name: "야구장 직관단",
    description: "야구 직관 함께해요!",
    category: "스포츠직관",
    tags: ["야구", "직관", "경기", "서울"],
    imageUrl: "",
  },
];

export const dummyNewCrews = Array.from({ length: 30 }, (_, i) => ({
  id: i,
  name: "사이클링히트",
  description: "잠실 2030 여성 야구 직관 동호회",
  category: "스포츠직관",
  tags: ["스포츠직관", "서울", "여성", "야구"],
  imageUrl: "",
  createdAt: new Date(Date.now() - i * 86400000).toISOString(), // 최신순 정렬용
}));
